spring.application.name=tp2-spring-mvc-jpa
spring.datasource.url=jdbc:h2:mem:products-db
spring.datasource.username=la
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8084
spring.h2.console.enabled=true